[package]
name = "ironic-space-lisp"
version = "0.1.0"
authors = ["Andrew Amis <atamiser@gmail.com>"]

[dependencies]
error-chain = {version = "0.12.0"}

[dependencies.nom]
version = "^4.0"
features = ["regexp_macros", "verbose-errors"]

