use std::str::FromStr;
use data::Literal;
use data::list;

grammar;

pub Num: Literal = r"[0-9]+" => Literal::Number(u32::from_str(<>).unwrap());

// [a-zA-Z0-9\-!?*+/$<>.=]
// can't start with number
pub Keyword: Literal = r"[a-zA-Z\-!?*+/$<>.=][a-zA-Z0-9\-!?*+/$<>.=]*" => Literal::Keyword(<>.to_string());

pub List: Literal = "(" <Exprs> ")" => list(<>);

pub Expr: Literal = {
    Num => <>,
    Keyword => <>,
    List => <>,
}

pub Exprs: Vec<Literal> = <Expr*> => <>;
