cargo-features = ["default-run"]

[package]
name = "isl"
version = "0.1.0"
authors = ["Andrew Amis <atamiser@gmail.com>"]
default-run = "isl"

[dependencies]
failure = "0.1.2"
im = "11.0.1"
rustyline = "2.0.0"
clap = "~2.32"
derive_is_enum_variant = "0.1.1"
nom = "^4.0"