cargo-features = ["default-run"]

[package]
name = "isl"
version = "0.1.0"
authors = ["Andrew Amis <atamiser@gmail.com>"]
default-run = "isl"

[dependencies]
failure = "0.1.2"
im = "12.1.0"
rustyline = "4.0.0"
clap = "~2.32"
derive_is_enum_variant = "0.1.1"
nom = "^4.0"
futures = "0.1"
tokio = "0.1"
rand = "0.5.5"
# Semi-lockless hashmap.
#chashmap = "2.2.0
