[package]
name = "isl-suite"
version = "0.1.0"
authors = ["Andrew Amis <atamiser@gmail.com>"]
#edition = "2018"

[dependencies]
isl = { path = "../isl" }
toml = "0.4"
serde = "1.0.79"
serde_derive = "1.0.79"
handlebars = "1.0.4"
